#!/usr/bin/env bash

name='./files/fun family party - 2023-10-03.jpg'

bname=${name##*/}
text=$(echo "$bname" | cut -d - -f 1)
date=$(echo "$bname" | cut -d - -f 2- | cut -d . -f 1 | xargs echo)

echo "$date: $text"
