#!/usr/bin/env bash

regex='^.*\/(.*) - ([0-9]{4}-[0-9]{2}-[0-9]{2})\..*$'

for name in files/*; do
	[[ $name =~ $regex ]] || exit 1

	text=${BASH_REMATCH[1]}
	date=${BASH_REMATCH[2]}
	echo "$date: $text"
done
