#!/usr/bin/env bash

name='./files/fun family party - 2023-10-03.jpg'

regex='^.*\/(.*) - ([0-9]{4}-[0-9]{2}-[0-9]{2})\..*$'

if [[ $name =~ $regex ]]; then
	text=${BASH_REMATCH[1]}
	date=${BASH_REMATCH[2]}
	echo "$date: $text"
fi
